export function prefetchHomeViewModules(): void {
  void import('@/components/organism/DashboardSection')
  void import('@/components/organism/CostsView')
  void import('@/components/organism/CostsAnalyzeView')
  void import('@/components/organism/IamUsersView')
  void import('@/components/organism/IamAccessKeysView')
  void import('@/components/organism/VulnerabilitiesView')
  void import('@/components/organism/VulnerabilitiesView/Ec2ServerDetailContent')
  void import('@/components/organism/OpenPortsView')
  void import('@/components/organism/S3PublicBucketsView')
  void import('@/components/organism/S3EncryptionStatusView')
  void import('@/components/organism/LambdaPublicFunctionsView')
  void import('@/components/organism/AcmExpiringCertificatesView')
  void import('@/components/organism/ElbPublicListenersView')
  void import('@/components/organism/EcrRepositoryRisksView')
  void import('@/components/organism/Ec2Imdsv1InstancesView')
  void import('@/components/organism/RdsUnencryptedInstancesView')
  void import('@/components/organism/RdsNoBackupsView')
  void import('@/components/organism/Ec2UnusedSecurityGroupsView')
  void import('@/components/organism/Ec2UnattachedVolumesView')
  void import('@/components/organism/UntaggedResourcesView')
  void import('@/components/organism/ResourcesByProjectTagView')
}
